export default {
    getProductsRequest: "GET_PRODUCTS_REQUEST",
    getProductSuccess: "GET_PRODUCTS_SUCCESS",
    getProductFailure: "GET_PRODUCTS_FAILURE",
    updateProductRequest: "UPDATE_PRODUCT_REQUEST",
    updateProductSuccess: "UPDATE_PRODUCT_SUCCESS",
    updateProductFailure: "UPDATE_PRODUCT_FAILURE",
    getProductPagesNumber: "GET_PRODUCT_PAGES_NUMBER",
    setProductPagesNumber: "SET_PRODUCT_PAGES_NUMBER",
    setProductsList: "SET_PRODUCTS_LIST",
    setProductsPage: "SET_PRODUCTS_PAGE",
    addProduct: "ADD_PRODUCT",
    addProductSuccess: "CREATE_PRODUCT_SUCCESS",
    addProductFailure: "CREATE_PRODUCT_FAILURE",
    resetProducts: "RESET_PRODUCTS",
    deleteProduct: "DELETE_PRODUCT",
    setCurrentStatus: "SET_CURRENT_STATUS",
    setErrorMessage: "SET_ERROR_MESSAGE",
}