export default {
    getProductsRequest: "GET_PRODUCTS_REQUEST",
    getProductsSuccess: "GET_PRODUCTS_SUCCESS",
    getProductsFailure: "GET_PRODUCTS_FAILURE",
    updateProductRequest: "UPDATE_PRODUCT_REQUEST",
    updateProductSuccess: "UPDATE_PRODUCT_SUCCESS",
    updateProductFailure: "UPDATE_PRODUCT_FAILURE",
    getProductPagesNumber: "GET_PRODUCT_PAGES_NUMBER",
    setProductPagesNumber: "SET_PRODUCT_PAGES_NUMBER",
    setProductsList: "SET_PRODUCTS_LIST",
    setProductsPage: "SET_PRODUCTS_PAGE",
    addProduct: "ADD_PRODUCT",
    addProductSuccess: "CREATE_PRODUCT_SUCCESS",
    addProductFailure: "CREATE_PRODUCT_FAILURE",
    resetProducts: "RESET_PRODUCTS",
    deleteProduct: "DELETE_PRODUCT",
    setCurrentAction: "SET_CURRENT_ACTION",
    setErrorMessage: "SET_ERROR_MESSAGE",
    setQueryParams: "SET_QUERY_PARAMS",
    showEditingModal: "SHOW_EDITING_MODAL",
    closeEditingModal: "CLOSE_EDITING_MODAL",
    setCurrentProduct: "SET_CURRENT_PRODUCT"
}