export default {
    registrationRequest: "USER_REGISTRATION_REQUEST",
    registrationSuccess: "USER_REGISTRATION_SUCCESS",
    registrationFailure: "USER_REGISTRATION_FAILURE",
    loginRequest: "USER_LOGIN_REQUEST",
    loginSuccess: "USER_LOGIN_SUCCESS",
    loginFailure: "USER_LOGIN_FAILURE",
    logout: "USER_LOGOUT",
    deleteRequest: "USER_LOGIN_REQUEST",
    deleteSuccess: "USER_LOGIN_SUCCESS",
    deleteFailure: "USER_LOGIN_FAILURE",
    getAllUsersRequest: "GET_ALL_USERS_REQUEST",
    getAllUsersSuccess: "GET_ALL_USERS_SUCCESS",
    getAllUsersFailure: "GET_ALL_USERS_FAILURE",
    setCurrentStatus: "SET_CURRENT_STATUS",
    setErrorMessage: "SET_ERROR_MESSAGE",
}